### ISSUE TITLE
[Question] No definition of angularSpeedMax/Min and angularAcceleration/DecelerationMax in physicalParameters ?

### ISSUE THREAD

**Issue by MeetYyj** [VDA5050/VDA5050#117]
I see velocity contains attribute omega means AGV's turning speed, but physicalParameters do not have angularSpeedMax/Min and angularAcceleration/DecelerationMax.

**Comment by KIT-IFL** [comment]
The proposed optional variables were introduced in the release candidate for Version 2.1.0 with the two parameters angularSpeedMin and angularSpeedMax in PR #277. The core team decided against acceleration and deceleration, since there was no real use case for those. If any can be provided, please reopen the issue.
