### ISSUE TITLE
which qos level is recommended for instantActions?

### ISSUE THREAD

**Issue by luanrp** [VDA5050/VDA5050#130]
"To reduce the communication overhead, the MQTT QoS level 0 (Best Effort) is to be used for the topics order, state, factsheet and visualization. The topic connection shall use the QoS level 1 (At Least Once)."

there is no QoS definition for instantActions. I guess 0 will be OK?

**Comment by ralienpp** [comment]
If you care about the action, use at least QoS `1`, because `0` means that the message **may not be delivered at all**.

For example, if you send an "emergency stop" signal - failure to deliver it could lead to safety issues. But if you tell the AGV to "change its ringtone", for example, it wouldn't be a big deal if the message gets lost.

In other words, choose the QoS based on the importance of the message itself.

**Comment by luanrp** [comment]
got it, that's quite reasonable, thanks!
