### ISSUE TITLE
Time Syncronization

### ISSUE THREAD

**Issue by JWCS** [VDA5050/VDA5050#172]
It's been mentioned in a few other issues as a pre-requisite to more advanced actions, with some sort of future action pending or waiting, but there's no specified actions or instant actions to do time synchronization.
In practice, I've seen a client call our getTime routine every 10sec or so, to make sure the system is synchronized, and we could port this functionality to our implementation of the VDA 5050 spec with custom / proprietary actions, but it seems like a commonly applicable feature.
As for the specific implementation, our tentative ideas are either a `ping`-like or setTimestamp instant action from the master control, or a small heartbeat-like ping request from the vehicle (payload as small as the current timestamp).

**Comment by Pythocrates** [comment]
Time synchronization is not in the scope of this standard IMO. Does your setup not allow for a dedicated time synchronization like NTP or something more elaborate/precise?

**Comment by JWCS** [comment]
We face two issues, one where we control the MC, but want to use 3rd party "VDA 5050 compatible" robots we don't have otherwise software support or control upon, and the issue when our "VDA 5050 compatible" robots have (at the moment) no online way to make sure the time is synchronized, for the reporting timestamps.
I can assume that the MC can be accurately sync'd to current UTC time, but that's not to be assumed for robots.
This is all to say, when all you have is VDA 5050, because that's the selling or integrating feature, and no control of the other side, there's no explicit VDA 5050 api / action that allows for timestamp exchanges.
On our setup, when we control the MC and the robot and the software on both, can do whatever we like, with or without VDA 5050. But that's not the point.

**Comment by Pythocrates** [comment]
I got the point of "all you have is VDA 5050" and "no online way" now. But introducing actions in the standard to do things usually taken care of by basis system services feels like an anti-pattern. AFAIK no action so far relies on synchronized clocks (talking from experience). If someone decides to introduce such an action, it is up to them to make sure they are synchronized.
Maybe this kind of pre-requisites would be something to add to the "factsheet" topic. But having some server sharing the NTP time is a well-established practice. If the MC is running in the same network, it could share its own time. Otherwise, any other computer can be set up to do that (without the need to expose the robots to the internet).
