### ISSUE TITLE
Two definitions for the ActionParameter object

### ISSUE THREAD

**Issue by JWCS** [VDA5050/VDA5050#190]
There are currently two objects defined for the ActionParameter object.
For Order/Node|Edge/Action(s), there's an ActionParameter array, with each ActionParameter object requiring a `key: string; value: string` pair.
This is (unhelpfully) not explicitly listed with the action definition under section 6.7 (Order Implementation), but under 7.2 (Format of Parameters).

For Factsheet/AgvProtocolFeatures/AgvAction(s), there's an ActionParameter array, with each ActionParameter object requiring a `key: string; valueDatatype: enum string; description: optional string; isOptional: optional bool`, under section 6.16.1 (Factsheet JSON strcture [sic]). 

It seems more clear to give one object a different name in the documentation, to disambiguate. IMO, the second type seems more like an ActionParameterDescription.

**Comment by KIT-IFL** [comment]
This is, in fact, a different definition of the actionParameter. In the factsheet, a more fitting name would have been ActionParameterDefinition, since the action parameters are defined here, that later on can be used in the Actions. Since renaming the parameters would be a breaking change, this is listed as one of the possible changes in Version 3.0. For the proposed document in Version 2.1.0, a clarification was added to show, that there are two different definitions of this parameter and how they are to be used.
