### ISSUE TITLE
Ambiguity regarding new orders that are handled as order updates

### ISSUE THREAD

**Issue by ralienpp** [VDA5050/VDA5050#20]
In Figure 8, when following the highlighted path, the last action is “append state…”. It is not stated explicitly whether 
(a) the sequence numbers of the nodes and edges are _automatically adjusted by the AGV_ (i.e. sequence numbers in the order will begin with 0 and the AGV will figure out the rest, e.g., by adding the last used sequence number)
(b) the MC is supposed to send a new order that _continues the sequence numbers_ from the value last used in the previous order.

![image](https://user-images.githubusercontent.com/295338/114684843-9d0fdf00-9d11-11eb-924c-10c4ff9f958e.png)

**Comment by MaximilianRies** [comment]
Hello Ralienpp,

the MC needs to take care of the right numbering of the sequence numbers.
They were added as an additional check to alleviate problems that may arise if a packet gets lost.

**Comment by ralienpp** [comment]
Hmm..., wouldn't it be easier to remove this scenario altogether? That is, if the MC wants to update an order - it sends an order update, instead of sending a new order that pretends to be an update.

What is gained by adding more flexibility in interpretation here?

**Comment by stephanlante** [comment]
Discussion within VDA and VDMA started

**Comment by MaximilianRies** [comment]
So, we discussed this during the last meeting and I think we can clarify some things here.

First, a quick picture that explains what we actually want to achieve with this path:

![change_order_id_with_update](https://user-images.githubusercontent.com/73341078/129364296-b0e2409e-991f-41d9-b595-dbc473681af2.png)

Note that we do not know which sequenceId's we have to give the RED nodes and edges.

The reason for changing the orderId of a running order were stated as follows:
- Vehicle must not stop for productivity reasons
- The orderId should actually reflect what the vehicle is doing at the moment (so just updating the base indefinitly is not an option)
- For some vehicles the vehicle will stop if it has an empty base.

Now, the (in my personal opinion) sanest solution is to just create a new order that starts on the last base node.
![approach_1_new_order](https://user-images.githubusercontent.com/73341078/129364914-39124981-3403-471b-b6b3-656474ae2c42.png)
This is basically what @ralienpp proposes in https://github.com/VDA5050/VDA5050/issues/20#issuecomment-854494401.

The problem with this is that the vehicle has to actually realize that the last node if its current order is the first node of the next order - and then decide to happily keep on trucking. Apparently, that is not that easy.

Which leads us to the flow that we have in the flowchart.
But: As others have already noted, this is also a bit of a pain, since we do not know which sequence numbers to choose.
During the discussion there were two approaches.

![approach_2_start_at_x](https://user-images.githubusercontent.com/73341078/129365349-3b23e799-a243-4314-a276-b1be3368e52b.png)

This approach solves the problem by just continueing the sequenceId's. This seems reasonable, but might mess with the initial order validation, since now you have to check if the order is an orderUpdate, if the orderUpdate fits to the current base, and if the sequenceId's are in proper sequence.

Another approach that was suggested is approach number 3.
![approach_3_start_at_0](https://user-images.githubusercontent.com/73341078/129365686-75411c3e-78ec-4359-8d03-f5c7c66ab493.png)
Here we just reset the nodeSequenceId's which *might* keep the validation happy, but opens a whole other can of worms, because: what is the edgeSequenceId with the three ??? in this case?

I think at this point it makes sense to have people chime in that actually need the order continuation path.
Anybody?

**Comment by MaximilianRies** [comment]
Hello all,

this was resolved in https://github.com/VDA5050/VDA5050/commit/5d3f6e24a53098aef4558d4030f04ae0aa0e34ef after long discussions. The path with the unconventional orderId change method is removed, since it brings more problems than it solves.

Thank you all for your helpful input.

**Comment by Hofmann-Christian** [comment]
just to keep in mind: this will end up in a stop behaviour of the AGV for a short moment.
