### ISSUE TITLE
Does VDA5050 MIT license?

### ISSUE THREAD

**Issue by kamidox** [VDA5050/VDA5050#291]
Hello, 

I have two questions.

1) Does this document is under MIT license?
2) In case 1) is true, does it means that the official publised VDA5050 is also a MIT license?

Or, a more general questions: Can we take VDA5050 as an input, and to convert it as a Country Standard?

Best Reagards
Joey

**Comment by AntonDueck** [comment]
the stuff on github is MIT so you could use it. 

the Official Documents from VDMA and VDA say:
![image](https://github.com/VDA5050/VDA5050/assets/86237773/ff6d0447-b882-486d-bc21-da5508e99d7e)


so you can use ist. as a base for a national Standard. But better you use it as it is und every vendor is happy  because there support your standard.

**Comment by KIT-IFL** [comment]
Please note that this repository is under the MIT license, which primarily governs the use of software components like the JSON schemas. However, the rules of the VDA mentioned above apply to the document itself. If you have any doubts or questions, I recommend reaching out to the responsible persons at the VDA directly [here](https://www.vda.de/en/topics/automotive-industry/vda-5050).
