### ISSUE TITLE
GIT Support for older versions

### ISSUE THREAD

**Issue by philipkirmse** [VDA5050/VDA5050#335]
Older products will continue to work with VDA5050 Versions v1.1 and v2.0. After release of 2.1.0 it is unclear if released branches for 1.1 and 2.0 are matching 100% released version of VDA5050 especially Schema files etc.

for example Version 2.0.0 RELEASE CANDIDATE, FOR REVIEW!!, 

Schema for 1.1 ar not available on branch for 1.1.0 etc.

There will be still developments necessary and not all vendors will move their AGV product from e.g. 1.1.0 to a newer VDA5050 version. So in my opinion all definition should stay available here.

Schemas in Branch 2.0.0 which says released are 3 years old and are not matching to final release. They are mismaching of PDF and Schemas which brings back this issues for example.

https://github.com/VDA5050/VDA5050/issues/195
https://github.com/VDA5050/VDA5050/issues/85

Request to have a final released branche for all released versions of VDA5050, that always a Bug free version is available with all connected files and Schemas. If there are Bugs (not enhancements) reported e.g. mistakes in document or deviation between Schemas and written document in my opinion also older released VDA5050 versions need to be patched by pull requests because this versions are basis of developments.

@KIT-IFL

**Comment by KIT-IFL** [comment]
Thank you for pointing this out and for your request. We have defined a clean process for the future so that such a migration error will no longer occur.
With regard to the schemas, we are currently correcting the errors in version 2.0 according to the PDF version of VDA 5050 published by the VDA. It is important to note that only the version published by the VDA is valid. These changes will be added by the end of the week through a pull request.
Schemas are only available from version 2.0; no rework is currently planned for version 1.1.

**Comment by KIT-IFL** [comment]
With PR #333 the json schemas were updated to incorporate all bugfixes. Please excuse this brief period of confusion. In the future, we will always make the appropriate changes in the release branch when it comes to bugs that are not included in the published PDF version.
@philipkirmse If you have the time, we would highly appreciate it, if you review the updated version of the schemas. Since we fixed additional bugs, that were not yet dealt with, we want to make sure, the schemas are still functional. Thank you and best regards!
