### ISSUE TITLE
Order reassignment differs between VDA5050 spec and vda-5050-lib.js

### ISSUE THREAD

**Issue by voztaka** [VDA5050/VDA5050#342]
According to VDA 5050 v2.1.0 (section 6.6.4.3),  it says that 

> "if master control doesn't receive a state message in time, it should be able to resend the order. The specification mentions that if an AGV receives the same order (same orderId and orderUpdateId) twice, the second order will be ignored"

However, I've noticed that when using [vda-5050-lib.js](https://github.com/coatyio/vda-5050-lib.js) (by Siemens), there seems to be a limitation: I cannot reassign an order even I need to retry sending it. Once an order is successfully published to MQTT, any subsequent request with the same AGV ID, order ID, and order update Id is ignored. 

So should the library be modified to align with the VDA 5050 specification's concept?

I would appreciate any insights or clarification on this matter.

**Comment by njoye** [comment]
@voztaka I'm assuming that this issue should be moved to the vda-5050-lib.js repository so that they can either fix what is broken or add your request as a feature. From what you understand you're correct. The master control (based on the specification) should be able to resend the order if there's no state message received in time. How the authors of the vda-5050-lib.js repo decide to implement this is their own choice and has nothing to do with this repository as far as I'm aware.

**Comment by HyundukChoi-Tim** [comment]
@njoye 
Thank you for your response. I have a good understanding of VDA5050's intended functionality, and I will reach out to the vda-5050-lib.js team about this issue. Really appreciate your help!

**Comment by voztaka** [comment]
@njoye 
Thanks for your response. I now have a clear understanding of VDA 5050's intended functionality, and I'll reach out to the vda-5050-lib.js team about this issue. Really appreciate your help!

**Comment by njoye** [comment]
@voztaka If your questions have been resolved, please close the issue :)
