### ISSUE TITLE
Reqest Fact Sheet from Vehicle

### ISSUE THREAD

**Issue by AntonDueck** [VDA5050/VDA5050#64]
A new/unknown vehicle connect to the MQTT Brocker and Publisches the first VDA5050 State. As an reaction on this the Master Control sends an Instant Action  RequestFactSheet with the Parameter {"key":  "URI" , "value":  "https://myserver/facksheetEndpoint" } 

the vehicle gets the Action and and starts an POST transfer to the URI with the payload (factsheet.json)
after the HTTP_OK(OK) is finish,  the action marked as successful in the vehicle state. 

![test](https://user-images.githubusercontent.com/86237773/134037141-cb0c2418-905d-4f4c-9597-8c01e12ab511.png)

**Comment by ralienpp** [comment]
Wouldn't it be preferred for the fact sheet to be returned by the device itself? [as opposed to redirecting to another resource, which may not be reachable]

**Comment by AntonDueck** [comment]
there is an security reason, not to have an webserver an the vehicle. you Secure an central server and not X server from different vendors.  
You do not know the IP Address/DNS Name of the AGV, only an VDA Serial Number. 

The process is similar to map server from VDA5051

If you assume the resource is unavailable (Central Rest Server) then you have to assume that your MQTT Broker is unavailable so you can do nothing, and then you do no need the factsheet also.

**Comment by ralienpp** [comment]
The AGV could return its fact-sheet by publishing a message over MQTT, i.e. use the same channel that is already available. Thus there's no need to start a new server anywhere.

**Comment by AntonDueck** [comment]
the problem if the fact sheet get big, but if the size is no problem then I would also prefer the MQTT solution

**Comment by LukasSchwarz4202** [comment]
Our current approach is to include the factsheet in the connection topic. Reasons for that:
- connection topic is hardly ever sent => does not add so much load to the network
- connection topic is retained => even if the AGV is already offline you can still access it
- connection topic is the first telegram the MC receives from the AGV. It can then immediately process it

**Comment by AntonDueck** [comment]
the Topic Connection is not the right position because it is resend every 15 SEC
See 6.14

**Comment by LukasSchwarz4202** [comment]
> the Topic Connection is not the right position because it is resend every 15 SEC
> See 6.14

6.14 only states that the heartbeat-interval to detect the disconnection should be set to 15 seconds, not that the connection telegramm should be resent every 15 seconds! (`The disconnection is detected via a heartbeat that is exchanged between the broker and the client. The interval is configurable in most brokers and should be set around 15 seconds.`)

The connection telegram should only be sent in the following three cases:
- AGV connected to broker => ONLINE
- AGV disconnected from broker => OFFLINE
- Connection to broker broke => CONNECTIONBROKEN (via last will mechanism)

So if you operate a AGV that does not have major connection problems and has to reconnect again all the time it is sent exactly two times: on connection and on disconnection.

**Comment by AntonDueck** [comment]
@LukasSchwarz4202  you are totally right. then if the payload size is not a problem this is a god way to go.

**Comment by collani-bosch** [comment]
It is a common security scheme to but the AGV into a separate network and restrict the IP-traffic with a firewall. One restriction is to block all connection attempts into the separate network (e.g. to prevent port scans or other attacks). Outgoing connections are possible (e.g. to the MQTT-Broker). Therefore the vehicle shall open the connection to MC and not vice versa.
Using MQTT would be charming, because we would stay at a singe communication protocol.

**Comment by ralienpp** [comment]
Re-purposing the `connection` topic is something I'd like to avoid, because it goes beyond the scope of what this topic was defined for. What's wrong with adding another topic for this purpose?

It could work like this:
- AGV connects to the broker
- AGV publishes its fact sheet to `<topicPrefix>/factSheet` as a message with `retain=True`

Benefits:
- this only needs to be done once, the broker will take care of storing this
- whoever subscribes to the topic will always get the most recent version of the published fact sheet
- there is no need to add a "request fact sheet" primitive; the AGV will always send it (and if it doesn't support this feature, it does not post the message - so there is nothing that would complicate matters from the point of backwards compatibility).

**Comment by MaximilianPenninger** [comment]
> A new/unknown vehicle connect to the MQTT Brocker and Publisches the first VDA5050 State. As an reaction on this the Master Control sends an Instant Action RequestFactSheet with the Parameter {"key": "URI" , "value": "https://myserver/facksheetEndpoint" }
> 
> the vehicle gets the Action and and starts an POST transfer to the URI with the payload (factsheet.json) after the HTTP_OK(OK) is finish, the action marked as successful in the vehicle state.
> 
> ![test](https://user-images.githubusercontent.com/86237773/134037141-cb0c2418-905d-4f4c-9597-8c01e12ab511.png)

Shouldn't that be resolved by the Version 2.0.0 and the /factsheet Topic?
