### ISSUE TITLE
Mismatch between json-schema and markdown in AllowedDeviationXY(y)

### ISSUE THREAD

**Issue by jabbenseth** [VDA5050/VDA5050#85]
The NodePosition Object according to Markdown has a property
AllowedDeviationXY (https://github.com/VDA5050/VDA5050/blob/f6d7f7996616fce7fbdf00552e7684e0980124d1/VDA5050_EN_V1.md?plain=1#L702) whereas the json schema defines it as AllowedDeviationXy (https://github.com/VDA5050/VDA5050/blob/f6d7f7996616fce7fbdf00552e7684e0980124d1/json_schemas/order.schema#L114)

**Comment by nsteffens** [comment]
This question was also asked at https://github.com/VDA5050/vd-m-a-5050/issues/23. I'm asking myself, if this will be resolved, because this actually leads to issues in the communication.

Can we please agree on something? I think 99.9% of users don't care what way is went, however, 99.9% care that the way is clearly defined. Alignment is the reason why this standard is used, and such derivations should be resolved IMO.

Since the original issue (see above) was opened over half a year ago, I'm really wondering if and when we will see these clarifications.

We also see a message by @collani-bosch (rf. above-mentioned issue), saying that the schemas should be the source of truth. Can we finally agree on something here, to actually bring the standard forward? Are pull requests to adopt the documentation appreciated or does this need to go through some standardization committee? It would be great to finally have some clarification here. 

Linking @KIT-IFL @LukasSchwarz4202  as the maintainers of this repository.

**Comment by PatrikStein** [comment]
@jabbenseth @nsteffens 
As discussed yesterday at the VDA5050 - it will be called "allowedDeviationXy" and must be renamed in the VDA5050 documentation.

Explanation: 
Xy has to be handled as a term (e.g. "XyCoordinates" or "XyPosition"), therefore it needs to be written in camel case.

fyi @ConstantinUp @MaxRies

**Comment by lenhartd** [comment]
@PatrikStein @jabbenseth 
When do you plan to do that? Do you have some sort of release planning for when this issue will be resolved? The branches still show a 2.0.0 review even though it was released. Is there an overview what kind of changes 3.0.0 or any other version in between will bring?

> @jabbenseth @nsteffens As discussed yesterday at the VDA5050 - it will be called "allowedDeviationXy" and must be renamed in the VDA5050 documentation.
> 
> Explanation: Xy has to be handled as a term (e.g. "XyCoordinates" or "XyPosition"), therefore it needs to be written in camel case.
> 
> fyi @ConstantinUp @MaxRies

**Comment by ChristophZeltnerExt** [comment]
Is there a timeline for this issue to be resolved in the document? 
It has been a while and the topic apparently has already been discussed.

**Comment by jabbenseth** [comment]
I'll close this old issue since it has been addressed in #208 to be allowedDeviationXY and is unified in dev/2.1.0

Also linking #229 since I read it as a duplicate (and #195)
